version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "vrtlmdn.io"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
    build:
        commands:
            - echo Build started on `date`
            - npm run build ${BUILD_ENV}
    post_build:
         commands:
            - aws s3 sync ./dist s3://${S3_BUCKET}
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
